### PR TITLE
Dependency upgrades

### PR DESCRIPTION
**Pull request by Taig**
I intended to just update the slick dependency, but had to modify the test as well because it kept failing for me.

### CODE REVIEW

**Comment by d6y** [comment]
Thanks for the PR!  Looks good.

I'm wondering if we should mark the dependencies as `provided` so that slickness doesn't force a particular version of Slick (and perhaps shapeless) on anyone.

Any thoughts on that? @davegurnell @jonoabroad also?

**Comment by davegurnell** [comment]
I'm happy to try it. No idea if it'll break things though.

**Comment by d6y** [comment]
OK - well maybe we should merge this one (version number bump required), and I can test out the `% provided` thing in a different PR.

**Comment by jonoabroad** [comment]
if no one has done this. I have it ready, including version bump.

**Comment by d6y** [comment]
Thanks @jonoabroad +1 on that.

**Comment by jonoabroad** [comment]
Done.

Thank you @Taig  for the PR.

**Pull request merged**
